name: Docker build huginn image

on:
  workflow_dispatch:

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - name: Get latest commit hash
        id: get-latest-commit
        run: |
          echo "::set-output name=commit::$(git ls-remote https://github.com/huginn/huginn.git | head -n1 | awk '{print $1;}')"
        shell: bash

      - uses: actions/cache@v2
        id: cache
        with:
          path: keel
          key: ${{ runner.os }}-v1-${{ steps.get-latest-commit.outputs.commit }}-${{ hashFiles('**/lockfiles') }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
        if: steps.cache.outputs.cache-hit != 'true'
        with:
          platforms: all

      - name: Check Out Repo
        uses: actions/checkout@v2

      - name: Check Out Repo huginn/huginn
        uses: actions/checkout@v2
        if: steps.cache.outputs.cache-hit != 'true'
        with:
          repository: "huginn/huginn"
          ref: 'master'
          path: 'huginn-git'
          
      - name: Dockerhub login
        env:
            DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
            DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        run: |
            echo "${DOCKER_PASSWORD}" | docker login --username ${DOCKER_USERNAME} --password-stdin

      - name: Set up Docker Buildx
        if: steps.cache.outputs.cache-hit != 'true'
        id: buildx
        uses: docker/setup-buildx-action@v1
        with:
          version: latest

      - name: Set up build timestamp
        if: steps.cache.outputs.cache-hit != 'true'
        run: echo "timestamp=$(date +%Y%m%d)" >> $GITHUB_ENV

      - name: Override prepare script
        id: override-prepare-script
        if: steps.cache.outputs.cache-hit != 'true'
        run: |
          cp huginn/scripts/prepare huginn-git/docker/scripts/prepare
          cp huginn/multi-process/scripts/standalone-packages huginn-git/docker/multi-process/scripts/standalone-packages
        shell: bash

      - name: Downgrade libv8
        if: steps.cache.outputs.cache-hit != 'true'
        run: |
          mv ./huginn/patches/*.patch ./huginn-git
          git config --global user.email "you@example.com"
          git config --global user.name "Your Name"
          cd ./huginn-git && git am *.patch
        shell: bash

      - name: Build and push docker image single process
        if: steps.cache.outputs.cache-hit != 'true'
        id: docker_build_new_single_process
        uses: docker/build-push-action@v2
        with:
          context: ./huginn-git
          file: ./Dockerfiles/huginn-dockerfile
          platforms: linux/amd64,linux/arm/v7,linux/arm64/v8
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/huginn-single-process:latest, ${{ secrets.DOCKER_USERNAME }}/huginn-single-process:build-${{ env.timestamp }}