# 编译marktext develop分支
name: marktext-build

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    
    env:
      MARKTEXT_IS_STABLE: 1
      MARKTEXT_EXIT_ON_ERROR: 1
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    steps:
        # 拉取仓库
      - name: Checkout
        uses: actions/checkout@v2
        with:
          repository: marktext/marktext
          ref: develop

        # 安装 node.js
      - name: Install node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14
          check-latest: true
          cache: yarn
          cache-dependency-path: yarn.lock

        # 修复 node-gyp
      - name: Fix node-gyp
        run: |
          npm install --global node-gyp@latest
          npm prefix -g | % {npm config set node_gyp "$_\node_modules\node-gyp\bin\node-gyp.js"}
          node-gyp install
        shell: pwsh

        # 缓存 node_modules
      - name: Cache node_modules
        uses: actions/cache@v2
        id: cacheNodeModules
        with:
          path: ${{ github.workspace }}\node_modules
          key: ${{ runner.os }}-node_modules-cache-v1-${{ hashFiles(format('{0}{1}', github.workspace, '\yarn.lock')) }}
          restore-keys: |
            ${{ runner.os }}-node_modules-cache-v1-

        # 缓存 Electron
      - name: Cache Electron
        uses: actions/cache@v2
        with:
          path: ${{ env.LOCALAPPDATA }}\electron\Cache
          key: ${{ runner.os }}-electron-cache-${{ hashFiles(format('{0}{1}', github.workspace, '\yarn.lock')) }}

        # 缓存 Electron-Builder
      - name: Cache Electron-Builder
        uses: actions/cache@v2
        with:
          path: ${{ env.LOCALAPPDATA }}\electron-builder\cache
          key: ${{ runner.os }}-electron-builder-cache-${{ hashFiles(format('{0}{1}', github.workspace, '\yarn.lock')) }}

        # 安装依赖
      - name: Install dependencies
        if: ${{ steps.cacheNodeModules.outputs.cache-hit != 'true' }}
        run: yarn install --check-files --frozen-lockfile

        # 构建
      - name: Build and release
        run: |
          yarn run release:win --publish always

      - name: Calculate checksums
        run: |
          get-filehash -Algorithm SHA256 "build\marktext-setup.exe"
          get-filehash -Algorithm SHA256 "build\marktext-*-win.zip"
        shell: pwsh

        # 设置版本号
      - name: Set version
        id: version
        run: |
          $version=((Get-Content "package.json") | ConvertFrom-Json).version
          echo "version=$version" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append
          $buildtime=(Get-Date).ToString('yyyy.MM.dd')
          echo "buildtime=$buildtime" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append

        # 发布
      - name: Release
        uses: ncipollo/release-action@v1
        with:
          tag: marktext-v${{ env.version }}_alpha.${{ env.buildtime }}
          name: marktext-v${{ env.version }}_alpha.${{ env.buildtime }}
          body: Github Action auto build.
          artifacts: build\marktext-setup.exe
          token: ${{ secrets.GITHUB_TOKEN }}
